package eu.trentorise.smartcampus.jp.timetable;

import it.sayservice.platform.smartplanner.data.message.otpbeans.Id;
import it.sayservice.platform.smartplanner.data.message.otpbeans.Route;

import java.util.ArrayList;
import java.util.List;

public class TTConfig {
	public static List<Route> getBusLines(){
		List <Route> returnList=new ArrayList<Route>();
		Route routeA =new Route();
		Id idA = new Id();
		idA.setAgency("12");
		idA.setId("_A");
		routeA.setId(idA);
		routeA.setRouteShortName("A");
		routeA.setRouteLongName("P.Dante - Osp.S.Chiara - Clarina - P.Dante");
		returnList.add(routeA);
		Route routeB =new Route();
		Id idB = new Id();
		idB.setAgency("12");
		idB.setId("_B");
		routeB.setId(idB);
		routeB.setRouteShortName("B");
		routeB.setRouteLongName("Piazza Dante - Laste - Piazza Dante");
		returnList.add(routeB);
		Route routeC =new Route();
		Id idC = new Id();
		idC.setAgency("12");
		idC.setId("C");
		routeC.setId(idC);
		routeC.setRouteShortName("C");
		routeC.setRouteLongName("SERVIZIO  EX   OSPEDALINO");
		returnList.add(routeC);
		Route routeDA =new Route();
		Id idDA = new Id();
		idDA.setAgency("12");
		idDA.setId("Da");
		routeDA.setId(idDA);
		routeDA.setRouteShortName("D");
		routeDA.setRouteLongName("SERVIZIO R.S.A: PORTA NUOVA - S.BARTOLOMEO");
		returnList.add(routeDA);
		Route routeDR =new Route();
		Id idDR = new Id();
		idDR.setAgency("12");
		idDR.setId("Dr");
		routeDR.setId(idDR);
		routeDR.setRouteShortName("D");
		routeDR.setRouteLongName("SERVIZIO R.S.A.: S.BARTOLOMEO - VIA GRAZIOLI");
		returnList.add(routeDR);
		Route routeNP =new Route();
		Id idNP = new Id();
		idNP.setAgency("12");
		idNP.setId("NPA");
		routeNP.setId(idNP);
		routeNP.setRouteShortName("NP");
		routeNP.setRouteLongName("NAVETTA PARCHEGGI: zuffo - m.te baldo - zuffo");
		returnList.add(routeNP);
		Route route01 =new Route();
		Id id01 = new Id();
		id01.setAgency("12");
		id01.setId("01");
		route01.setId(id01);
		route01.setRouteShortName("1");
		route01.setRouteLongName("Roncafort - P.Dante - Osp.S.Chiara- Roncafort");
		returnList.add(route01);
		Route route02 =new Route();
		Id id02 = new Id();
		id02.setAgency("12");
		id02.setId("02");
		route02.setId(id02);
		route02.setRouteShortName("2");
		route02.setRouteLongName("Vela - P.Dante - Osp.S.Chiara - P.Dante -Vela");
		returnList.add(route02);
		Route route03A =new Route();
		Id id03A = new Id();
		id03A.setAgency("12");
		id03A.setId("03A");
		route03A.setId(id03A);
		route03A.setRouteShortName("3");
		route03A.setRouteLongName("Cortesano - Gardolo - P.Dante - Villazzano 3");
		returnList.add(route03A);
		Route route03R =new Route();
		Id id03R = new Id();
		id03R.setAgency("12");
		id03R.setId("03R");
		route03R.setId(id03R);
		route03R.setRouteShortName("3");
		route03R.setRouteLongName("Villazzano 3 - P.Dante - Gardolo - Cortesano");
		returnList.add(route03R);
		Route route04A =new Route();
		Id id04A = new Id();
		id04A.setAgency("12");
		id04A.setId("04A");
		route04A.setId(id04A);
		route04A.setRouteShortName("4");
		route04A.setRouteLongName("Madonna Bianca - Via Degasperi - Piazza Dante");
		returnList.add(route04A);
		Route route04R =new Route();
		Id id04R = new Id();
		id04R.setAgency("12");
		id04R.setId("04R");
		route04R.setId(id04R);		
		route04R.setRouteShortName("4");
		route04R.setRouteLongName("Piazza Dante - Via Degasperi - Madonna Bianca");
		returnList.add(route04R);
		Route route05A =new Route();
		Id id05A = new Id();
		id05A.setAgency("12");
		id05A.setId("05A");
		route05A.setId(id05A);
		route05A.setRouteShortName("5");
		route05A.setRouteLongName("Piazza Dante - P.Fiera - Povo - Oltrecastello");
		returnList.add(route05A);
		Route route05R =new Route();
		Id id05R = new Id();
		id05R.setAgency("12");
		id05R.setId("05R");
		route05R.setId(id05R);		
		route05R.setRouteShortName("5");
		route05R.setRouteLongName("Oltrecastello - Povo - P.Aquila - P.Dante");
		returnList.add(route05R);
		Route route06A =new Route();
		Id id06A = new Id();
		id06A.setAgency("12");
		id06A.setId("06A");
		route06A.setId(id06A);
		route06A.setRouteShortName("6");
		route06A.setRouteLongName("Sopramonte - P.Dante - Villazzano - Grotta");
		returnList.add(route06A);
		Route route06R =new Route();
		Id id06R = new Id();
		id06R.setAgency("12");
		id06R.setId("06R");
		route06R.setId(id06R);
		route06R.setRouteShortName("6");
		route06R.setRouteLongName("Grotta - Villazzano - P.Dante - Sopramonte");
		returnList.add(route06R);
		Route route07A =new Route();
		Id id07A = new Id();
		id07A.setAgency("12");
		id07A.setId("07A");
		route07A.setId(id07A);
		route07A.setRouteShortName("7");
		route07A.setRouteLongName("Canova - Melta - Piazza Dante - Gocciadoro");
		returnList.add(route07A);
		Route route07R =new Route();
		Id id07R = new Id();
		id07R.setAgency("12");
		id07R.setId("07R");
		route07R.setId(id07R);
		route07R.setRouteShortName("7");
		route07R.setRouteLongName("Gocciadoro - Piazza Dante - Melta - Canova");
		returnList.add(route07R);
		Route route08A =new Route();
		Id id08A = new Id();
		id08A.setAgency("12");
		id08A.setId("08A");
		route08A.setId(id08A);
		route08A.setRouteShortName("8");
		route08A.setRouteLongName("Mattarello -  Piazza Dante -  Centochiavi");
		returnList.add(route08A);
		Route route08R =new Route();
		Id id08R = new Id();
		id08R.setAgency("12");
		id08R.setId("08R");
		route08R.setId(id08R);
		route08R.setRouteShortName("8");
		route08R.setRouteLongName("Centochiavi - Piazza Dante - Mattarello");
		returnList.add(route08R);
		Route route09A =new Route();
		Id id09A = new Id();
		id09A.setAgency("12");
		id09A.setId("09A");
		route09A.setId(id09A);
		route09A.setRouteShortName("9");
		route09A.setRouteLongName("P.Dante - S.Donà - Cognola - Villamontagna");
		returnList.add(route09A);
		Route route09R =new Route();
		Id id09R = new Id();
		id09R.setAgency("12");
		id09R.setId("09R");
		route09R.setId(id09R);
		route09R.setRouteShortName("9");
		route09R.setRouteLongName("Villamontagna - Cognola - S.Donà - P.Dante");
		returnList.add(route09R);
		Route route10A =new Route();
		Id id10A = new Id();
		id10A.setAgency("12");
		id10A.setId("10A");
		route10A.setId(id10A);
		route10A.setRouteShortName("10");
		route10A.setRouteLongName("Cognola / Montevaccino - Martignano - P.Dante");
		returnList.add(route10A);
		Route route10R =new Route();
		Id id10R = new Id();
		id10R.setAgency("12");
		id10R.setId("10R");
		route10R.setId(id10R);
    	route10R.setRouteShortName("10");
		route10R.setRouteLongName("P.Dante - Martignano - Cognola / Montevaccino");
		returnList.add(route10R);
		Route route11A =new Route();
		Id id11A = new Id();
		id11A.setAgency("12");
		id11A.setId("11A");
		route11A.setId(id11A);
		route11A.setRouteShortName("11");
		route11A.setRouteLongName("Spini di Gardolo - Via Brennero - P.Dante");
		returnList.add(route11A);
		Route route11R =new Route();
		Id id11R = new Id();
		id11R.setAgency("12");
		id11R.setId("11R");
		route11R.setId(id11R);
		route11R.setRouteShortName("11");
		route11R.setRouteLongName("Piazza Dante / Roncafort - Gardolo - Spini");
		returnList.add(route11R);
		Route route12A =new Route();
		Id id12A = new Id();
		id12A.setAgency("12");
		id12A.setId("12A");
		route12A.setId(id12A);
		route12A.setRouteShortName("12");
		route12A.setRouteLongName("Romagnano - Ravina - Via Ghiaie - P.Dante");
		returnList.add(route12A);
		Route route12R =new Route();
		Id id12R = new Id();
		id12R.setAgency("12");
		id12R.setId("12R");
		route12R.setId(id12R);
		route12R.setRouteShortName("12");
		route12R.setRouteLongName("P.Dante - Via Ghiaie - Ravina - Romagnano");
		returnList.add(route12R);
		Route route13A =new Route();
		Id id13A = new Id();
		id13A.setAgency("12");
		id13A.setId("13A");
		route13A.setId(id13A);
		route13A.setRouteShortName("13");
		route13A.setRouteLongName("P.Dante - Rosmini - S.Rocco - Povo polo soc.");
		returnList.add(route13A);
		Route route13R =new Route();
		Id id13R = new Id();
		id13R.setAgency("12");
		id13R.setId("13R");
		route13R.setId(id13R);
		route13R.setRouteShortName("13");
		route13R.setRouteLongName("Povo - S.Rocco - Rosmini - Piazza Dante");
		returnList.add(route13R);
		Route route14A =new Route();
		Id id14A = new Id();
		id14A.setAgency("12");
		id14A.setId("14A");
		route14A.setId(id14A);
		route14A.setRouteShortName("14");
		route14A.setRouteLongName("Belvedere Ravina - Via Sanseverino - P.Dante");
		returnList.add(route14A);
		Route route14R =new Route();
		Id id14R = new Id();
		id14R.setAgency("12");
		id14R.setId("14R");
		route14R.setId(id14R);
		route14R.setRouteShortName("14");
		route14R.setRouteLongName("P.Dante - Via Sanseverino - Belvedere Ravina");
		returnList.add(route14R);
		Route route15A =new Route();
		Id id15A = new Id();
		id15A.setAgency("12");
		id15A.setId("15A");
		route15A.setId(id15A);
		route15A.setRouteShortName("15");
		route15A.setRouteLongName("Piazza Dante - Interporto - Spini di Gardolo");
		returnList.add(route15A);
		Route route15R =new Route();
		Id id15R = new Id();
		id15R.setAgency("12");
		id15R.setId("15R");
		route15R.setId(id15R);
		route15R.setRouteShortName("15");
		route15R.setRouteLongName("Spini di Gardolo - Interporto - Piazza Dante");
		returnList.add(route15R);
		Route route16A =new Route();
		Id id16A = new Id();
		id16A.setAgency("12");
		id16A.setId("16A");
		route16A.setId(id16A);
		route16A.setRouteShortName("16");
		route16A.setRouteLongName("Povo-Cognola-Martignano-Centochiavi");
		returnList.add(route16A);
		Route route16R =new Route();
		Id id16R = new Id();
		id16R.setAgency("12");
		id16R.setId("16R");
		route16R.setId(id16R);
		route16R.setRouteShortName("16");
		route16R.setRouteLongName("Centochiavi-Martignano-Cognola-Povo");
		returnList.add(route16R);
		Route route17A =new Route();
		Id id17A = new Id();
		id17A.setAgency("12");
		id17A.setId("17A");
		route17A.setId(id17A);
		route17A.setRouteShortName("17");
		route17A.setRouteLongName("Piazza Dante - Via Bolzano - Lavis");
		returnList.add(route17A);
		Route route17R =new Route();
		Id id17R = new Id();
		id17R.setAgency("12");
		id17R.setId("17R");
		route17R.setId(id17R);
		route17R.setRouteShortName("17");
		route17R.setRouteLongName("Lavis - S.Lazzaro -  Piazza Dante");
		returnList.add(route17R);
	return returnList;
	};
}
